# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [4]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [5]:
array1d = np.array([1,2,3,4])
print(array1d)

array2d = np.array([[1,1,1,1], [2,2,2,2]])
print(array2d)

array3d = np.array([[[1,1],[2,2],[3,3]]])
print(array3d)

[1 2 3 4]
[[1 1 1 1]
 [2 2 2 2]]
[[[1 1]
  [2 2]
  [3 3]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [6]:
fun_array = np.array([1,3,5])
#Dimmensions .ndim
print(fun_array.ndim)

print(fun_array.shape)

#amount of elements .size
print(fun_array.size)

#prints the type of elements in the array .dtype
print(fun_array.dtype)

print(fun_array.itemsize)

print(fun_array.data)

#the amount of bytes used .nbytes
print(fun_array.nbytes)


1
(3,)
3
int32
4
12


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [7]:
# creats an 2x6 array filled with 1's.
arrayof1s = np.ones((2,6))
print(arrayof1s)

##Create an array of zeros that is size 2x2.
arrayzeros = np.zeros((2,2))
print(arrayzeros)

#Still doesn't show the dimmensions.
arrayempty =np.empty((10,10))
print(np.empty)

#fill array with with a specified values. Idk if you can do strings.
arrayfilled = np.full((10, 5), np.inf)
print(arrayfilled)

#Returns a new array of evenly spaced values within a given interval
#arange uses the interval distance as 1 unless otherwise specified
arrayarange = np.arange(0,11)
print(arrayarange)

Arangarray = np.arange(4)
print(Arangarray)


#np.linspace(): Returns a new array of evenly spaced numbers over a specified interval
arraylinspace = np.linspace(0,10, 10)
print(arraylinspace)

#return a single random value or an array of random values between 0 and 1. *10 at the end to make larger values
randoarray = np.random.random((5,4))*10
print(randoarray)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
<built-in function empty>
[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[[8.90146993 4.98474275 6.78499712 5.89464562]
 [0.87369422 6.97372963 2.93819046 3.86909232]
 [4.4952136  6.3456257  2.91711375 2.10289488]
 [3.35631887 0.79234209 0.52057739 8.29776273]
 [0.43079096 2.28506504 1.64968981 3.70452959]]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [8]:
arrayone = np.ones((4,4))
arraytwo = np.random.random((1,4))
result = arrayone + arraytwo
print(result)


arraybad = np.ones((3,3))
arrayworse = np.linspace(0,10,1)
#Confused why linspace is making it look like this
np.shape(arrayworse)
badresult = arraybad + arrayworse
print(arrayworse)
print(badresult)

[[1.16958129 1.8918607  1.12550842 1.80124447]
 [1.16958129 1.8918607  1.12550842 1.80124447]
 [1.16958129 1.8918607  1.12550842 1.80124447]
 [1.16958129 1.8918607  1.12550842 1.80124447]]
[0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [9]:
filler =np.full((5,5), 4)
randos = np.random.random((5,5))*10
oness = np.ones((6,6))

print(np.sum(filler))
print(np.sum(filler+randos)) 

print("randoos")
print(randos)
print(np.mean(randos))
print(np.cumsum(randos))
print(np.std(randos))


print(np.mean(oness))
print(np.std(oness))

z = np.corrcoef(funx, funy)
print(z)

## This is the the co-variance function

funx = np.array([[10, 3], [2,8]])
funx
funy = np.array([[5, 8], [3,13]])
funy
xy = np.stack((funx, funy), axis = 0)
np.cov(funx, funy)

100
200.7614723955444
randoos
[[6.41091442 3.4351737  0.59703482 2.08622638 8.45222937]
 [0.73646478 4.93943014 3.26294826 4.74883743 0.07003386]
 [7.74350372 0.41839122 0.29255694 9.50702282 8.56885984]
 [2.10691407 4.21290517 2.70779272 5.77262776 2.58368783]
 [5.96330533 3.16754095 4.26998524 0.88244382 7.82464181]]
4.030458895821775
[  6.41091442   9.84608812  10.44312294  12.52934932  20.98157869
  21.71804347  26.65747361  29.92042186  34.66925929  34.73929316
  42.48279688  42.90118809  43.19374504  52.70076785  61.26962769
  63.37654176  67.58944692  70.29723964  76.0698674   78.65355523
  84.61686057  87.78440152  92.05438676  92.93683058 100.7614724 ]
2.831666764590652
1.0
0.0


NameError: name 'funx' is not defined

## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [10]:
booleanarray = [True, True, False, False]
b = [False, False, True, True]
np.ndim(booleanarray)
c=[1,1,1,1]
## don't really see why they return these values

np.logical_and(booleanarray, b)
np.logical_or(c, booleanarray)

array([ True,  True,  True,  True])

In [12]:
coolarray = np.arange(35)
print(coolarray)

coolarray.shape = (7,5)
coolarray






coolarray[-2]
row = 5
column = 2
coolarray[row, column]
np.ndim(coolarray) # the literal dimmension 2d


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


2