# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [12]:
array1d = np.array([1,2,3,4])
print(array1d)

array2d = np.array([[1,1,1,1], [2,2,2,2]])
print(array2d)

array3d = np.array([[[1,1],[2,2],[3,3]]])
print(array3d)

[1 2 3 4]
[[1 1 1 1]
 [2 2 2 2]]
[[[1 1]
  [2 2]
  [3 3]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [26]:
fun_array = np.array([1,3,5])
#Dimmensions .ndim
print(fun_array.ndim)

print(fun_array.shape)

#amount of elements .size
print(fun_array.size)

#prints the type of elements in the array .dtype
print(fun_array.dtype)

print(fun_array.itemsize)

print(fun_array.data)

#the amount of bytes used .nbytes
print(fun_array.nbytes)


1
(3,)
3
int32
4
12


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [65]:
# creats an 2x6 array filled with 1's.
arrayof1s = np.ones((2,6))
print(arrayof1s)

##Create an array of zeros that is size 2x2.
arrayzeros = np.zeros((2,2))
print(arrayzeros)

#Still doesn't show the dimmensions.
arrayempty =np.empty((10,10))
print(np.empty)

#fill array with with a specified values. Idk if you can do strings.
arrayfilled = np.full((10, 5), np.inf)
print(arrayfilled)

#Returns a new array of evenly spaced values within a given interval
#arange uses the interval distance as 1 unless otherwise specified
arrayarange = np.arange(0,11)
print(arrayarange)

Arangarray = np.arange(4)
print(Arangarray)


#np.linspace(): Returns a new array of evenly spaced numbers over a specified interval
arraylinspace = np.linspace(0,10, 10)
print(arraylinspace)

#return a single random value or an array of random values between 0 and 1. *10 at the end to make larger values
randoarray = np.random.random((5,4))*10
print(randoarray)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
<built-in function empty>
[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[[0.26256579 2.42276408 7.25832335 0.60968948]
 [8.00469297 6.85881968 9.18283092 0.02399943]
 [8.5485416  0.60970653 6.87954738 7.3394503 ]
 [8.17504012 5.22420496 4.84056632 1.56259877]
 [2.19722396 8.89084028 0.38122773 5.95332406]]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [98]:
arrayone = np.ones((4,4))
arraytwo = np.random.random((1,4))
result = arrayone + arraytwo
print(result)


arraybad = np.ones((3,3))
arrayworse = np.linspace(0,10,1)
#Confused why linspace is making it look like this
np.shape(arrayworse)
badresult = arraybad + arrayworse
print(arrayworse)
print(badresult)

[[1.10439211 1.40532582 1.38207728 1.82519165]
 [1.10439211 1.40532582 1.38207728 1.82519165]
 [1.10439211 1.40532582 1.38207728 1.82519165]
 [1.10439211 1.40532582 1.38207728 1.82519165]]
[0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [143]:
filler =np.full((5,5), 4)
randos = np.random.random((5,5))*10
oness = np.ones((6,6))

print(np.sum(filler))
print(np.sum(filler+randos)) 

print("randoos")
print(randos)
print(np.mean(randos))
print(np.cumsum(randos))
print(np.std(randos))


print(np.mean(oness))
print(np.std(oness))

z = np.corrcoef(funx, funy)
print(z)

## This is the the co-variance function

funx = np.array([[10, 3], [2,8]])
funx
funy = np.array([[5, 8], [3,13]])
funy
xy = np.stack((funx, funy), axis = 0)
np.cov(funx, funy)

100
198.83269582706953
randoos
[[2.81707165 0.43413497 7.58743145 0.33942385 5.10000874]
 [1.49802933 3.50501785 6.00415907 8.21444914 5.24541947]
 [9.50104392 4.61610765 4.03983061 0.01442253 1.6379994 ]
 [6.76607424 1.16320553 3.18796171 4.77506448 5.13103462]
 [4.64631659 6.09224095 0.80719811 1.72149265 3.98755732]]
3.9533078330827816
[ 2.81707165  3.25120662 10.83863807 11.17806192 16.27807066 17.77609999
 21.28111784 27.28527692 35.49972606 40.74514552 50.24618945 54.8622971
 58.90212771 58.91655023 60.55454963 67.32062387 68.4838294  71.67179111
 76.44685559 81.57789021 86.2242068  92.31644775 93.12364586 94.84513851
 98.83269583]
2.5447930009658695
1.0
0.0
[[ 1. -1. -1. -1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]]


array([[ 24.5, -21. , -10.5, -35. ],
       [-21. ,  18. ,   9. ,  30. ],
       [-10.5,   9. ,   4.5,  15. ],
       [-35. ,  30. ,  15. ,  50. ]])

## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [183]:
booleanarray = [True, True, False, False]
b = [False, False, True, True]
np.ndim(booleanarray)
c=[1,1,1,1]
## don't really see why they return these values

np.logical_and(booleanarray, b)
np.logical_or(c, booleanarray)

array([ True,  True,  True,  True])

In [184]:
coolarray = np.arange(35)
print(coolarray)

coolarray.shape = (7,5)
coolarray






coolarray[-2]
row = 5
column = 2
coolarray[row, column]
np.itemsize(coolarray)
np.ndim(coolarray) # the literal dimmension 2d


array([False, False, False, False])