# Numpy.  Part 1
### Arrays

Use the following attributes:
    ndim,
    shape,
    size,
    dtype,
    itemsize,
    data,
    nbytes,

In [3]:
import numpy as np

fun_array = np.array([1,3,5])

print(fun_array.ndim)
print(fun_array.shape)
print(fun_array.size)
print(fun_array.dtype)
print(fun_array.itemsize)
print(fun_array.data)
print(fun_array.nbytes)


1
(3,)
3
int32
4
12


### Initializing Arrays

In [4]:
# Creates a 2x6 array filled with 1's.
arrayof1s = np.ones((2,6))
print(arrayof1s)

## Create an array of zeros that is size 2x2.
arrayzeros = np.zeros((2,2))
print(arrayzeros)

## Fill array with with a specified values. Idk if you can do strings. 
arrayfilled = np.full((10, 5), np.inf)
print(arrayfilled)

## Returns a new array of evenly spaced values within a given interval
## arange uses the interval distance as 1 unless otherwise specified
arrayarange = np.arange(0,11)
print(arrayarange)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]
[ 0  1  2  3  4  5  6  7  8  9 10]


### Math/Stats Aggregate Functions

Use the following aggregation functions: sum, minimum, maximum, cumsum, mean, np.corrcoef, np.std, np.var

In [5]:
filler =np.full((5,5), 4)
randos = np.random.random((5,5))*10
oness = np.ones((6,6))

print(np.sum(filler))
print(np.sum(filler+randos)) 

print("randoos")
print(randos)
print(np.mean(randos))
print(np.cumsum(randos))
print(np.std(randos))


print(np.mean(oness))
print(np.std(oness))

## This is the the co-variance function

funx = np.array([[10, 3], [2,8]])
funx
funy = np.array([[5, 8], [3,13]])
funy

xy = np.stack((funx, funy), axis = 0)
np.cov(funx, funy)

z = np.corrcoef(funx, funy)
print(z)

100
237.9736880881287
randoos
[[5.78048814 4.97898207 8.87506751 6.62766818 1.42353912]
 [8.53651005 3.96018997 9.38580786 2.02603382 4.45962481]
 [3.66201338 4.92034481 1.82068023 2.83282393 8.42200081]
 [5.91377323 7.31975271 2.25209738 8.91610567 8.88432914]
 [9.24652186 3.52628094 7.86438979 3.98155426 2.35710842]]
5.5189475235251475
[  5.78048814  10.75947021  19.63453772  26.2622059   27.68574502
  36.22225507  40.18244505  49.56825291  51.59428673  56.05391154
  59.71592492  64.63626973  66.45694995  69.28977388  77.71177469
  83.62554792  90.94530063  93.19739801 102.11350368 110.99783282
 120.24435468 123.77063562 131.63502541 135.61657967 137.97368809]
2.647470221012791
1.0
0.0
[[ 1. -1. -1. -1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]]


# NumPy Part 2

Basic Indexing: Subsets and Slicing

##### Get items from "start" to "end" (but the end is not included!)
a[start:end] 

###### Get all items from "start" through the rest of the array
a[start:]    

##### Get items from the beginning to "end" (but the end is not included!)
a[:end]   

##### Get the last item from the last 'row':
a[-1, -1]

### Appending to an Array

In [6]:
new_one = np.ones((4,4))

new=np.append(new_one, [[0], [0]])
print(new)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]


### Inserting and Deleting Elements

In [ ]:
allones = np.ones((10,10))
print(allones)

np.insert(allones,0,0, axis = 0)
np.delete(allones, -1, axis = 0)

### A few useful functions

call help(), np.transpose(), np.reshape(), np.resize(), np.ravel(), np.append(), np.delete(), np.concatenate(), np.vstack(), np.hstack(), np.column_stack(), np.vsplit(), np.hsplit()

### Joining Arrays

In [7]:
# Concatentate `my_array` and `x`: similar to np.append()
# Concatenate's the 2 arrays together
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


### Splitting Arrays

In [8]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


### Reshaping an Array

In [9]:
shaper = np.ones((2,2))
print(shaper)
np.resize(shaper, (3,4))


shaper2 = np.zeros((8,2))
np.reshape(shaper2, (4,4))

[[1. 1.]
 [1. 1.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Pandas Part 1

+ Pandas Cheat Sheet
+ [Data Quest Pandas cheat sheet](./media/pandas-cheet-sheet.pdf)
+ [Data Camp cheat sheet](./media/pandas-cheet-sheet.pdf)

pd.head(), pd.tail(), pd.sample(), and pd.describe()

In [11]:
import pandas as pd

In [14]:
## Create the series object.
my_series = pd.Series([1, 3, 5, np.nan, 6, 8])
my_series

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [18]:
## Creating a dataframe with a dictionary.
df_1 = pd.DataFrame(
    {'alpha': [0, 1, 2, 3, 4],
     'beta': ['a', 'b', 'c', 'd', 'e']})
df_1

alpha beta
0      0    a
1      1    b
2      2    c
3      3    d
4      4    e

### Create a DataFrame with a Numpy array

In [15]:
df = pd.DataFrame(np.random.randn(6, 4))
df

0         1         2         3
0 -1.157182 -1.233485 -1.446705 -1.472978
1  0.307174  0.474843 -0.143991  0.045086
2  0.350213 -0.087046  1.179232 -0.181055
3 -0.419743  0.475897  0.988759 -0.589944
4  0.475359 -0.308651  0.183380 -0.580832
5  0.128684 -1.017575 -0.409059  0.410403

### Create a DataFrame with row and column labels
Rather than have a numeric index for each row and column of the DataFrame, we may want to give each row a human-readable label. This will help make the data more accessible (as will be seen later).  To demonstrate, lets reuse the 6x4 datafame we created in section 2.2.2. Using this dataset we want to rename the row indexes with hypothetical dates that each row of information was collected, and we want to give the columns names, such as `A1`, `A2`, `B1` and `C1`.  

First, let's set the row index names.  The code below uses the `pd.date_range` function to create a list of dates. Most likely, if we have dates in a real input dataset we would not be creating a list of dates, but for the purposes of demonstration we will generate a series of regularly spaces dates over a 6 day period: one for each of the 6 rows. Note that the `start` argument for the `pd.date_range` function expects the date in YYYYMMDD format.

###### pd.date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs) → pandas.core.indexes.datetimes.DatetimeIndex

In [21]:
dates = pd.date_range('20200301', periods=6)
print(dates)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=('A1','A2', 'B1', 'C1'))
df

DatetimeIndex(['2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04',
               '2020-03-05', '2020-03-06'],
              dtype='datetime64[ns]', freq='D')


A1        A2        B1        C1
2020-03-01 -0.625531 -2.936700 -0.790367 -0.268665
2020-03-02 -0.282703 -0.509609  1.239814 -0.089300
2020-03-03  1.988578  0.424629 -0.979049 -0.905124
2020-03-04  0.901499  1.766624  0.611972  0.659912
2020-03-05 -0.528187 -0.970592 -0.667780  0.297129
2020-03-06  2.402315  0.170012  1.081661  0.991660

### To use quarterly data in the index

In [31]:
dates1 = pd.date_range('19750301', periods=60, freq = 'QS')
df1 = pd.DataFrame(np.random.randn(60, 4), index=dates1, columns=('A1','A2', 'B1', 'C1'))
df1.sample(4)

A1        A2        B1        C1
1989-04-01 -0.482702 -0.359133 -1.699077 -0.210951
1986-01-01 -0.678817  0.381300  0.084559 -0.235659
1988-01-01  0.935037  0.751621 -0.116422  1.233526
1976-01-01 -0.911522 -0.830562  0.452793  0.547510

### Create DataFrame with labels

In [32]:
names = ("Joshua", "Ricky1", "Ricky2","Evan", "Gunnar", "Dane", " Student 7", "Student 8", "Student 9", "Student 10" )
AFSgrades = pd.DataFrame(np.random.normal(0.85, .2, (10, 5)), index=names, columns=('Midterm','Final Exam','Project','Homework','Extra Credit'))
AFSgrades

Midterm  Final Exam   Project  Homework  Extra Credit
Joshua      1.046225    0.968444  0.809950  1.162581      1.008440
Ricky1      0.855639    0.764653  0.987449  0.932649      0.624694
Ricky2      1.027834    0.717269  0.698582  0.769746      0.796632
Evan        0.883034    0.978274  0.588358  0.525857      0.805575
Gunnar      0.906944    1.300561  0.887670  0.831525      0.674512
Dane        0.751315    0.859218  0.549579  0.927726      0.876510
 Student 7  1.090285    0.730832  0.981342  0.592174      1.022499
Student 8   0.600187    0.669310  0.979880  0.855612      0.859918
Student 9   0.712127    0.861978  0.909783  1.128630      0.927352
Student 10  0.848136    0.931480  0.787592  0.725783      0.960793

### Get Values

In [33]:
iris = pd.read_csv(r"C:\Users\Joshu\afs505_u2\iris.csv")

#df.loc[row_start:row_end, column_start:column_end] <-- proper syntax 
iris.loc[0:0]     # Gets the first row
iris.loc[0:5]    # Gets the first 5 rows


iris_df.loc[[4,6], ['sepal_width', 'petal_width']]   #Grabs specific columns
iris_df.loc[4:6, ['sepal_width', 'petal_width']]     #Grabs a range of columns

######################### iloc #######################
#iris.iloc[:,0]          #Grabs the first column
#iris.iloc[3]            #Grabs the first 3 rows

iris.iloc[10:15, :-3]    #Grabs rows 10-15 and excludes the last 3 columns
#iris.columns           #Gets column names

iris_df.loc[4:6, 'sepal_width': 'petal_width']

# Pandas Part 2

### Inserting a New Column

In [36]:
# Add the new column
new_series = pd.Series([4, 3, 2, 1, 0])
df['gamma'] = new_series

# Now print the data frame
df

A1        A2        B1        C1  gamma
2020-03-01 -0.625531 -2.936700 -0.790367 -0.268665    NaN
2020-03-02 -0.282703 -0.509609  1.239814 -0.089300    NaN
2020-03-03  1.988578  0.424629 -0.979049 -0.905124    NaN
2020-03-04  0.901499  1.766624  0.611972  0.659912    NaN
2020-03-05 -0.528187 -0.970592 -0.667780  0.297129    NaN
2020-03-06  2.402315  0.170012  1.081661  0.991660    NaN

In [37]:
Alternatively you can use a numpy array instead of a Seris

SyntaxError: invalid syntax (<ipython-input-37-3b6b3dd5b5be>, line 1)

In [39]:
df = pd.DataFrame(
    {'alpha': [0, 1, 2, 3, 4],
     'beta': ['a', 'b', 'c', 'd', 'e']})

## Add column
df['gamma'] = np.array([4, 3, 2, 1, 0])
df

alpha beta  gamma
0      0    a      4
1      1    b      3
2      2    c      2
3      3    d      1
4      4    e      0

### Missing Data
https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#missing-data

### Dropping Rows with Missing Values

In [ ]:
df.dropna()

If you would like to have the data frame change "in place", then you then have two choices:
1. Use the `dropna` function's `inplace=True` argument.
2. Assign the result, using the same name.
    `df = df.dropna()`

Let's save the dataframe with rows removed into a new data frame:

In [40]:
# Drop the rows with missing values.
df_nomissing = df.dropna()
# Print the contents of our new data frame.
df_nomissing

alpha beta  gamma
0      0    a      4
1      1    b      3
2      2    c      2
3      3    d      1
4      4    e      0

### Filling Missing Values
In some cases, setting missing values to some other value (such as 0) may be appropriate. This can be accomplished using the df.fillna() function and passing in the desired value. Below we'll fill missing values with

In [55]:
df.fillna(0)

alpha beta  gamma
0      0    a      4
1      1    b      3
2      2    c      2
3      3    d      1
4      4    e      0

### Mathematical Operations

In [57]:
help(pd.DataFrame.mean)
# calcualte the mean of each row, and use the head function to only show the
# top 5 rows.
iris_df = pd.read_csv('iris.csv')
iris_df.mean()
iris_df.mean(1).head()
iris_df

iris_df.corr()
iris_df.median()
iris_df.var()
iris_df.std(axis=0)
iris_df.mean()

#Subest the data to exlude column 'species' because it is a string
DropCol5 = iris_df.filter(items=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
#Calculate the percecntage change from 1 period earlier (differencing but using percentage)
DropCol5.pct_change(1)

Sepal_sum = iris_df.filter(items=['sepal_length', 'sepal_width'])
Sepal_sum.apply(np.sum)


Help on function mean in module pandas.core.frame:

mean(self, axis=None, skipna=None, level=None, numeric_only=None, **kwargs)
    Return the mean of the values for the requested axis.
    
    Parameters
    ----------
    axis : {index (0), columns (1)}
        Axis for the function to be applied on.
    skipna : bool, default True
        Exclude NA/null values when computing the result.
    level : int or level name, default None
        If the axis is a MultiIndex (hierarchical), count along a
        particular level, collapsing into a Series.
    numeric_only : bool, default None
        Include only float, int, boolean columns. If None, will attempt to use
        everything, then use only numeric data. Not implemented for Series.
    **kwargs
        Additional keyword arguments to be passed to the function.
    
    Returns
    -------
    Series or DataFrame (if level specified)



sepal_length    876.5
sepal_width     458.1
dtype: float64

### Apply

Another common operation is the ability to "apply" another function to a set of rows or columns (or a subset created from slicing). To efficiently apply functions in this way there is the `df.apply()` function.  The list of arguments for the `df.apply()` function are shown below 

```python
apply(func, axis=0, broadcast=None, raw=False, reduce=None, result_type=None, args=(), **kwds)
```

In [51]:
#help(df.apply)
df.apply(print)
df.apply(type)
df.apply(np.sum)

0    0
1    1
2    2
3    3
4    4
Name: alpha, dtype: object
0    a
1    b
2    c
3    d
4    e
Name: beta, dtype: object
0    4
1    3
2    2
3    1
4    0
Name: gamma, dtype: object


alpha       10
beta     abcde
gamma       10
dtype: object

### Occurances

You can calculate the number of occurances for a set of values in a `pd.Series` object using the `value_counts` function.  These counts are similar to what you would see in a Histogram.  As an example, let's create a new series containing 10 random integers between 1 and 7. Then we will use `value_counts` to observe how many occurances there are of each integer.  First let's create the series:

In [52]:
s = pd.Series(np.random.randint(0, 7, size=10))
s
s.value_counts()



1    3
5    2
4    2
3    2
6    1
dtype: int64

#### Working with Strings in the DataFrame

Many times, data sets will have columns with string values that must be modified in some way, such as being split from one column into two, or joining columns into one. To demonstrate string methods, lets adjust the `df` object to add some strings.  As a reminder lets look at the df object:

### Working with Strings in the DataFrame

In [54]:
df
df.shape

(5, 3)

## Need to add this 
# String Methods

+ Create a list of five strings that represent dates in the form YYYY-MM-DD (e.g. 2020-02-20 for Feb 20th, 2020).
+ Add this list of dates as a new column in the `df` dataframe.
+ Now split the date into 3 new columns with one column representing the year, another the month and another they day.
+ Combine the values from columns `alpha` and `beta` into a new column where the values are spearated with a colon.


### Concatenation by Rows

In [63]:
df1 = pd.DataFrame(
  {'alpha': [0, 1, 2, 3, 4],
   'beta': ['a', 'b', 'c', 'd', 'e']}, index = ['I1', 'I2' ,'I3', 'I4', 'I5'])

df2 = pd.DataFrame(
{'delta' : [3, 6, 9, 12, 15],
'gamma' :['three', 'six', 'nine', 'twelve', 'fifteen']}, index = ['I1', 'I2', 'I3', 'Eye4', 'Eye5'])

df2.head()


## There are NaN because the two dfs have not merged their index.
## They each still retain their original index therefore have missing values

concate_df = pd.concat([df1, df2], axis=0, sort=True).reindex


### Concatenation by Columns

In [64]:
# Notice, an "inner" join removes rows whose index name is not present in both
df1['delta'] = [90, 80, 70, 60, 50]
df1
pd.concat([df1, df2], axis=1, sort = True)
pd.concat([df1, df2], axis=1, join='inner')


alpha beta  delta  delta  gamma
I1      0    a     90      3  three
I2      1    b     80      6    six
I3      2    c     70      9   nine

### Concat and append data frames

In [61]:
randos = pd.DataFrame(np.random.randint(0,100,size=(5, 5)), columns=list('ABCDE'))
randos

ones = pd.DataFrame(np.ones((5, 10)))
ones

## to append df2 at the end of df1 dataframe
appended_df = df1.append(df2, ignore_index = True)
appended_df

zeroseries = pd.Series([0,0,0,0,0])
append_again = appended_df.append(zeroseries, ignore_index = True)
append_again

C:\Users\Joshu\anaconda\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,


alpha beta  delta    gamma    0    1    2    3    4
0     0.0    a   90.0      NaN  NaN  NaN  NaN  NaN  NaN
1     1.0    b   80.0      NaN  NaN  NaN  NaN  NaN  NaN
2     2.0    c   70.0      NaN  NaN  NaN  NaN  NaN  NaN
3     3.0    d   60.0      NaN  NaN  NaN  NaN  NaN  NaN
4     4.0    e   50.0      NaN  NaN  NaN  NaN  NaN  NaN
5     NaN  NaN    3.0    three  NaN  NaN  NaN  NaN  NaN
6     NaN  NaN    6.0      six  NaN  NaN  NaN  NaN  NaN
7     NaN  NaN    9.0     nine  NaN  NaN  NaN  NaN  NaN
8     NaN  NaN   12.0   twelve  NaN  NaN  NaN  NaN  NaN
9     NaN  NaN   15.0  fifteen  NaN  NaN  NaN  NaN  NaN
10    NaN  NaN    NaN      NaN  0.0  0.0  0.0  0.0  0.0

## Grouping

Demonstrate a `groupby`.

+ Create a new column with the label "region" in the iris data frame. This column will indicates geographic regions of the US where measurments were taken. Values should include:  'Southeast', 'Northeast', 'Midwest', 'Southwest', 'Northwest'. Use these randomly.
+ Use `groupby` to get a new data frame of means for each species in each region.
+ Add a `dev_stage` column by randomly selecting from the values "early" and "late".
+ Use `groupby` to get a new data frame of means for each species,in each region and each development stage.
+ Use the `count` function (just like you used the `mean` function) to identify how many rows in the table belong to each combination of species + region + developmental stage.

In [62]:
iris_df['region']=np.random.choice(['Northeast', 'Midwest', 'Southwest', 'Northwest'], iris_df.shape[0])

groups = iris_df.groupby(['region'])
groups.mean()

iris_df['dev_stage'] = np.random.choice(['early', 'late'], iris_df.shape[0])
groups = iris_df.groupby(['species', 'dev_stage'])
groups.count()

sepal_length  sepal_width  petal_length  petal_width  \
species    dev_stage                                                         
setosa     early                21           21            21           21   
           late                 29           29            29           29   
versicolor early                27           27            27           27   
           late                 23           23            23           23   
virginica  early                32           32            32           32   
           late                 18           18            18           18   

                      region  
species    dev_stage          
setosa     early          21  
           late           29  
versicolor early          27  
           late           23  
virginica  early          32  
           late           18